#!/bin/python3

import math
import os
import random
import re
import sys
if __name__ == '__main__':
    n = int(input())
if (n%2)!=0:
    print("weird")
else:
    if n <= 5 :
        print("not weird")
    elif n <= 20 :
        print("weird")
    else:
        print("not weird")
