#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))

def bubblesort(a):
    n = len(a)
    allSwapCount = 0
    for i in range(0, n):
        swapCount = 0
        for j in range(0, n - 1):
            if a[j] > a[j + 1]:
                a[j], a[j+1] = a[j+1], a[j] 
                swapCount += 1
        if swapCount == 0:
            break
        else:
            allSwapCount += swapCount
    return (a[0], a[n - 1], allSwapCount)
first, last, swaps = bubblesort(a)
print("Array is sorted in", swaps, "swaps.")
print("First Element:", first)
print("Last Element:", last)
