#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        N = int(nk[0])

        K = int(nk[1])
        
        maximum = 0

        for j in range(1, N):
            for k in range(j + 1, N + 1):
                h = j & k
                if K > h > maximum:
                    maximum = h

        print(maximum)

